project:
  version: @project.version@
server:
  port: 8080
  servlet:
    context-path: /v1/
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:zaradb
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
spring-doc:
  version: 3.0.0

