CREATE TABLE IF NOT EXISTS PRICES
(
    BRAND_ID INT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(10, 2),
    CURR VARCHAR(3)
);

CREATE TABLE IF NOT EXISTS BRAND
(
    BRAND_ID INT NOT NULL,
    NAME VARCHAR(50) NOT NULL
)